Added auth complete flow
kapeiharshad/trade-management-api pull request #2
Opened 2022-07-20 19:22 UTC by kapeiharshad

1)Added auth api for users and admin.
2)Added login api with jwt verification.
3) Added change password api.
4) Added forget password api which will send email for verification.
5) Added its swagger and test cases.
6) Updated configuration of test and util file.

![test](https://user-images.githubusercontent.com/53931276/180064492-4e00efd1-aafc-4e6c-91dd-2e7684d0a70c.png)
![auth_swagger](https://user-images.githubusercontent.com/53931276/180064501-59578141-b5b8-478f-8beb-0e5c712f77d8.png)

2022-07-21 18:02 UTC, kapeiharshad commented on models/userToken.model.js
> +      enum: ['accessToken', 'refershToken', 'randToken'],
please update refreshToken name properly.

2022-07-22 15:05 UTC, pratikgupta9 requested changes

2022-07-22 15:05 UTC, pratikgupta9 commented on helpers/jwt.helper.js
> +    if (req.headers.authorization) {
iski zarurat lagg rahi hai yaha (req.headers && req.headers.authorization)

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +            token: token,
statusCode=200 missing

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +        success: false,
statusCode ki zaraurat hai yaha then add karna?

2022-07-22 15:05 UTC, pratikgupta9 commented on services/users.service.js
>            msg: 'User not founded.',
founded ko found kar na isme

2022-07-22 15:05 UTC, pratikgupta9 commented on services/users.service.js
>            msg: 'User not founded or deleted unsuccessfully.',
founded ko found karna bas

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +      return {
statusCode missing in this function

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +          return {
statusCode add karna

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +      return {
statusCode add karna

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +            success: true,
statusCode add karna

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +        success: true,
statusCode missing

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +      return {
statusCode missing

2022-07-22 15:05 UTC, pratikgupta9 commented on services/auth.service.js
> +  static async resetPasswordVerify({ body }) {
statusCode missing in this function

2022-07-22 18:00 UTC, kapeiharshad commented on services/auth.service.js
> +            token: token,
by default sucess has 200 response

2022-07-22 18:14 UTC, kapeiharshad commented on models/userToken.model.js
> +      enum: ['accessToken', 'refershToken', 'randToken'],
done

2022-07-22 18:14 UTC, kapeiharshad commented on helpers/jwt.helper.js
> +    if (req.headers.authorization) {
updated done.

2022-07-22 18:14 UTC, kapeiharshad commented on services/auth.service.js
> +        success: false,
done

2022-07-22 18:15 UTC, kapeiharshad commented on services/users.service.js
>            msg: 'User not founded.',
done

2022-07-22 18:15 UTC, kapeiharshad commented on services/users.service.js
>            msg: 'User not founded or deleted unsuccessfully.',
done

2022-07-22 18:16 UTC, kapeiharshad commented on services/auth.service.js
> +      return {
done

2022-07-22 18:19 UTC, kapeiharshad commented on services/auth.service.js
> +            success: true,
no need to add

2022-07-22 18:19 UTC, kapeiharshad commented on services/auth.service.js
> +        success: true,
no need to add

2022-07-22 18:19 UTC, kapeiharshad commented on services/auth.service.js
> +      return {
done

2022-07-22 18:19 UTC, kapeiharshad commented on services/auth.service.js
> +  static async resetPasswordVerify({ body }) {
no need to add

2022-07-22 18:30 UTC, merged