Category and product
kapeiharshad/trade-management-api pull request #3
Opened 2022-07-26 18:08 UTC by pratikgupta9

2022-07-26 18:09 UTC, pratikgupta9 commented
<img width="1440" alt="Screenshot 2022-07-26 at 11 38 40 PM" src="https://user-images.githubusercontent.com/54830570/181080060-ba2d8e48-906e-4ac5-8c72-5e4c54862dcb.png">
<img width="1440" alt="Screenshot 2022-07-26 at 11 38 57 PM" src="https://user-images.githubusercontent.com/54830570/181080096-a12c07e3-42b9-4039-9a29-1d341c62f380.png">

2022-07-26 19:13 UTC, kapeiharshad requested changes

2022-07-26 19:13 UTC, kapeiharshad commented on helpers/pagination.helper.js
> +  async generatePagination(model, queryParams, project = {}, statusQuery) {
default value parameters should always remain in last. here project should come after statusQuery

2022-07-26 19:13 UTC, kapeiharshad commented on helpers/util.helper.js
> +const uniqueId = require('generate-unique-id');
Here can we use nanoId instaed of generate-unique-id because it has more download and popularity then this npm. Please provide your thoughts.

2022-07-26 19:13 UTC, kapeiharshad commented on package.json
> +    "husky": "6",
is there is need of this?

2022-07-26 19:13 UTC, kapeiharshad commented on routes/users.route.js
> +router.patch('/:user Id', editUser, async (req, res) => {
there should be space in router path

2022-07-26 19:13 UTC, kapeiharshad commented on services/categories.service.js
> +      let oneCategory = await Category.findOne(
varaible type should be const instead of let

2022-07-26 19:13 UTC, kapeiharshad commented on services/categories.service.js
> +      let oneCategory = await Category.findOne(
varaible type should be const instead of let

2022-07-26 19:13 UTC, kapeiharshad commented on services/products.service.js
> +      let oneProduct = await Product.findOne(
varaible type should be const here

2022-07-26 19:13 UTC, kapeiharshad commented on services/products.service.js
> +      let oneProduct = await Product.findOne(
variable type should be const here

2022-07-26 19:15 UTC, kapeiharshad commented
@pratikgupta9 also add all swagger and test cases of routes.

2022-08-01 17:12 UTC, kapeiharshad commented on helpers/pagination.helper.js
> +  async generatePagination(model, queryParams, project = {}, statusQuery) {
done

2022-08-01 19:17 UTC, kapeiharshad commented on helpers/util.helper.js
> +const uniqueId = require('generate-unique-id');
replaced by uuid

2022-08-01 19:17 UTC, kapeiharshad commented on package.json
> +    "husky": "6",
changed to previous one

2022-08-01 19:17 UTC, kapeiharshad commented on routes/users.route.js
> +router.patch('/:user Id', editUser, async (req, res) => {
done

2022-08-01 19:17 UTC, kapeiharshad commented on services/categories.service.js
> +      let oneCategory = await Category.findOne(
done

2022-08-01 19:17 UTC, kapeiharshad commented on services/categories.service.js
> +      let oneCategory = await Category.findOne(
done

2022-08-01 19:17 UTC, kapeiharshad commented on services/products.service.js
> +      let oneProduct = await Product.findOne(
done

2022-08-01 19:18 UTC, kapeiharshad commented on services/products.service.js
> +      let oneProduct = await Product.findOne(
done

2022-08-07 03:37 UTC, pratikgupta9 commented
<img width="1440" alt="Screenshot 2022-08-07 at 9 01 57 AM" src="https://user-images.githubusercontent.com/54830570/183273927-15c6c18b-352e-407a-9458-c54d06d45904.png">
<img width="1440" alt="Screenshot 2022-08-07 at 9 06 52 AM" src="https://user-images.githubusercontent.com/54830570/183274031-d987981c-6ccd-4f46-8b41-65cb56380099.png">

2022-08-07 14:25 UTC, kapeiharshad approved these changes

2022-08-07 14:25 UTC, merged